#!/usr/bin/env python3
"""Generate the standalone Saab Marp theme bundled with this skill.

The repository theme (in the ``article_common_artifacts`` submodule) refers to
``url(themes/saab_logo_extracted.svg)`` and ``url(themes/cover_background.jpg)``
with *relative* paths, so a deck only renders correctly when it ships a
``themes/`` symlink next to it. This script produces a self-contained variant by

* inlining the logo and cover background as data URIs (no sibling files needed),
* keeping only the logo layer on regular slides and removing the baked-in
  classification strip (the deck front matter supplies it via ``footer:``), and
* dropping the override that cleared the logo on regular slides, so the Saab logo
  appears on *every* slide as in ``saab_template.pptx``.

Usage (from anywhere)::

    python3 scripts/make_theme.py \
        --source <path/to/saab-theme.css> \
        --logo  assets/brand/saab-logo.svg \
        --cover assets/brand/cover_background.jpg \
        --out   assets/theme/saab-theme.css
"""

from __future__ import annotations

import argparse
import base64
import re
import sys
from pathlib import Path

MIME = {
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
}


def data_uri(path: Path) -> str:
    mime = MIME.get(path.suffix.lower())
    if mime is None:
        raise SystemExit(f"unsupported asset type: {path}")
    blob = base64.b64encode(path.read_bytes()).decode("ascii")
    return f'url("data:{mime};base64,{blob}")'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    here = Path(__file__).resolve().parent
    skill = here.parent
    repo_root = skill.parents[2]  # .opencode/skills/<id> -> repository root
    parser.add_argument(
        "--source",
        type=Path,
        default=repo_root
        / "3rd_party/article_common_artifacts/pressentation/themes/saab/saab-theme.css",
        help="source @theme saab CSS (repo submodule theme by default)",
    )
    parser.add_argument("--logo", type=Path, default=skill / "assets/brand/saab-logo.svg")
    parser.add_argument(
        "--cover", type=Path, default=skill / "assets/brand/cover_background.jpg"
    )
    parser.add_argument("--out", type=Path, default=skill / "assets/theme/saab-theme.css")
    args = parser.parse_args()

    css = args.source.read_text(encoding="utf-8")

    # 1. Inline the relative brand images so the theme is location independent.
    logo = data_uri(args.logo)
    css = css.replace("url(themes/saab_logo_extracted.svg)", logo)
    css = css.replace("url(themes/cover_background.jpg)", data_uri(args.cover))

    # 2. Regular slides: keep the logo layer, drop the duplicate baked-in
    #    classification strip (the `footer:` directive renders it instead).
    m = re.search(r"(section \{\n.*?\n\})", css, re.S)
    if not m:
        raise SystemExit("could not locate the base `section {` block")
    base = m.group(1)
    new_base = re.sub(
        r'(background-image:\n    url\("data:image/svg\+xml;base64,[^"]*"\)),'
        r'\n    url\("data:image/svg\+xml;base64,[^"]*"\);',
        r"\1;",
        base,
    )
    new_base = new_base.replace("background-repeat: no-repeat, no-repeat;", "background-repeat: no-repeat;")
    new_base = new_base.replace("background-position: top right, bottom center;", "background-position: top right;")
    new_base = new_base.replace("background-size: 13% auto, 100% auto;", "background-size: 13% auto;")
    css = css.replace(base, new_base, 1)

    # 3. Remove the deck override that cleared the logo/footer on regular slides.
    css = re.sub(
        r"\nsection \{\n  /\* shorthand intentionally.*?\n\}\n",
        "\n",
        css,
        count=1,
        flags=re.S,
    )

    # 4. Refresh the documentation comment about relative paths.
    css = css.replace(
        "/* Relative image paths (`url(themes/...)`) resolve against the */\n"
        "/* deck's markdown file, so decks must ship their own           */\n"
        "/* `themes/saab_logo_extracted.svg` and `themes/cover_background.jpg`. */",
        "/* Standalone variant: the logo and cover are inlined below as  */\n"
        "/* data URIs, so the theme can be dropped anywhere. It is       */\n"
        "/* generated by scripts/make_theme.py — edit that, not this file. */",
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(css, encoding="utf-8")
    print(f"wrote {args.out} ({args.out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
